name = "Minecraft Beyond"
author = "DestroyerMob"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6aa97af9b04ae291dde5e1ba17b56b8dee41d48a687130cbfefb44f1f15de8a0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
