name = "Minecraft Beyond"
author = "DestroyerMob"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cea9546150e1c9a204909c2357c99430adbc6efa5f17d7bec24a2233aff71de4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
