name = "Minecraft Beyond"
author = "DestroyerMob"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db85fca8e1420d577bad5a6b85e6e1e772ee1b28b8ce0d7bfaba8864bfac4b50"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
