param(
    [switch]$Check
)

$ErrorActionPreference = 'Stop'

$workspace = Split-Path -Parent $PSScriptRoot
$manifestPath = Join-Path $workspace 'pack/kubejs/config/food_unification_groups.json'
$almostUnifiedRoot = Join-Path $workspace 'pack/config/almostunified'
$tagsPath = Join-Path $almostUnifiedRoot 'tags.json'
$foodConfigPath = Join-Path $almostUnifiedRoot 'unification/food.json'
$runtimeTargetsPath = Join-Path $workspace 'pack/kubejs/startup_scripts/food_unification_targets.js'
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function ConvertTo-StableJson {
    param([Parameter(Mandatory = $true)]$Value)

    return ($Value | ConvertTo-Json -Depth 20) + [Environment]::NewLine
}

function Assert-ResourceLocation {
    param(
        [Parameter(Mandatory = $true)][string]$Value,
        [Parameter(Mandatory = $true)][string]$Description
    )

    if ($Value -cnotmatch '^[a-z0-9_.-]+:[a-z0-9_./-]+$') {
        throw "Invalid $Description resource location: $Value"
    }
}

if (-not (Test-Path -LiteralPath $manifestPath -PathType Leaf)) {
    throw "Food unification manifest was not found: $manifestPath"
}

$parsedGroups = Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json
$groups = New-Object System.Collections.Generic.List[object]
foreach ($parsedGroup in $parsedGroups) {
    $groups.Add($parsedGroup)
}
if ($groups.Count -eq 0) {
    throw 'Food unification manifest is empty.'
}

$seenTags = @{}
$seenItems = @{}
$customTags = [ordered]@{}
$priorityOverrides = [ordered]@{}
$tagTargets = [ordered]@{}
$itemTargets = [ordered]@{}
$tagIds = New-Object System.Collections.Generic.List[string]

foreach ($group in $groups) {
    $tag = [string]$group.tag
    $canonical = [string]$group.canonical
    $items = @($group.items | ForEach-Object { [string]$_ })

    Assert-ResourceLocation -Value $tag -Description 'tag'
    Assert-ResourceLocation -Value $canonical -Description 'canonical item'

    if ($seenTags.ContainsKey($tag)) {
        throw "Duplicate food unification tag: $tag"
    }
    if ($items.Count -lt 2) {
        throw "Food unification group must contain at least two items: $tag"
    }
    if ($items[0] -cne $canonical) {
        throw "Canonical item must be first in group ${tag}: $canonical"
    }
    if ($items -cnotcontains $canonical) {
        throw "Canonical item is missing from group ${tag}: $canonical"
    }

    foreach ($item in $items) {
        Assert-ResourceLocation -Value $item -Description 'item'
        if ($seenItems.ContainsKey($item)) {
            throw "Item appears in both $($seenItems[$item]) and ${tag}: $item"
        }
        $seenItems[$item] = $tag
        $itemTargets[$item] = $canonical
    }

    $seenTags[$tag] = $true
    $customTags[$tag] = $items
    $priorityOverrides[$tag] = ($canonical -split ':', 2)[0]
    $tagTargets[$tag] = $canonical
    $tagIds.Add($tag)
}

$tagsConfig = [ordered]@{
    custom_tags = $customTags
    tag_substitutions = [ordered]@{}
    item_tag_inheritance_mode = 'ALLOW'
    item_tag_inheritance = [ordered]@{}
    block_tag_inheritance_mode = 'ALLOW'
    block_tag_inheritance = [ordered]@{}
    emi_strict_hiding = $true
}

$foodConfig = [ordered]@{
    mod_priorities = @(
        'minecraft',
        'bountifulfares',
        'farmersdelight',
        'brewinandchewin',
        'crabbersdelight',
        'culturaldelights',
        'ends_delight',
        'expandeddelight',
        'moredelight',
        'mynethersdelight',
        'oceansdelight',
        'bakery',
        'beachparty',
        'cornexpansion',
        'brewery',
        'candlelight',
        'farm_and_charm',
        'herbalbrews',
        'meadow',
        'naturalist',
        'spawn',
        'supplementaries',
        'vinery',
        'wildernature',
        'croptopia',
        'pamhc2crops',
        'pamhc2foodcore',
        'pamhc2foodextended',
        'pamhc2trees',
        'kubejs'
    )
    priority_overrides = $priorityOverrides
    stone_variants = @(
        'stone',
        'andesite',
        'deepslate',
        'diorite',
        'granite',
        'netherrack',
        'end_stone'
    )
    tags = @($tagIds)
    ignored_tags = @()
    ignored_items = @()
    ignored_recipe_types = @('cucumber:shaped_tag')
    ignored_recipe_ids = @(
        'farmersknives:emerald_knife',
        'farmersknives:copper_knife_et',
        'farmersknives:copper_knife_mm',
        'farmersknives:cincinnasite_knife_diamond',
        'letsdocompat:farmersdelight/farm_and_charm/pot_cooking/simple_tomato_soup',
        'farmersknives:copper_knife',
        'letsdocompat:farm_and_charm/cooking/ghostly_chili'
    )
    recipe_viewer_hiding = $true
    loot_unification = $true
    ignored_loot_tables = @()
}

$runtimeTargets = @(
    '// Generated by tools/generate-food-unification.ps1. Do not edit by hand.',
    ('global.FOOD_UNIFICATION_TAG_TARGETS = ' + ($tagTargets | ConvertTo-Json -Depth 20)),
    ('global.FOOD_UNIFICATION_ITEM_TARGETS = ' + ($itemTargets | ConvertTo-Json -Depth 20))
) -join [Environment]::NewLine
$runtimeTargets += [Environment]::NewLine

$expected = [ordered]@{
    $tagsPath = ConvertTo-StableJson -Value $tagsConfig
    $foodConfigPath = ConvertTo-StableJson -Value $foodConfig
    $runtimeTargetsPath = $runtimeTargets
}

if ($Check) {
    foreach ($entry in $expected.GetEnumerator()) {
        if (-not (Test-Path -LiteralPath $entry.Key -PathType Leaf)) {
            throw "Generated file is missing: $($entry.Key)"
        }
        $actual = [System.IO.File]::ReadAllText($entry.Key)
        if ($actual -cne $entry.Value) {
            throw "Generated file is stale: $($entry.Key)"
        }
    }
    Write-Host "Food unification config is current: $($groups.Count) groups, $($seenItems.Count) items."
    exit 0
}

[System.IO.Directory]::CreateDirectory((Split-Path -Parent $tagsPath)) | Out-Null
[System.IO.Directory]::CreateDirectory((Split-Path -Parent $foodConfigPath)) | Out-Null
[System.IO.Directory]::CreateDirectory((Split-Path -Parent $runtimeTargetsPath)) | Out-Null

foreach ($entry in $expected.GetEnumerator()) {
    [System.IO.File]::WriteAllText($entry.Key, $entry.Value, $utf8NoBom)
}

Write-Host "Generated Almost Unified food config: $($groups.Count) groups, $($seenItems.Count) items."
